version: "3.9"
services:
  frontend:
    build: ./frontend
    container_name: frontendappContainer
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true #Terminal Interaction
    tty: true
  backend:
    build: ./backend
    container_name: backendappContainer
    ports:
      - "7000:7000"
    volumes:
      - ./backend:/app
      - ./app/node_modules